#!/bin/bash
echo "Running local pre-push checks..."

# # Run tests
# echo "Running tests..."
# npm test
# if [ $? -ne 0 ]; then
#     echo "Tests failed. Push aborted."
#     exit 1
# fi

# Check for TODO comments
echo "Checking for TODOs..."
if grep -r --exclude-dir=hooks "TODO" ./src; then
    echo "Push aborted: TODO found in source files."
    exit 1
fi

echo "All checks passed. Proceeding with push."
exit 0